"""add_youtube_notification_table

Revision ID: 1a0ceda47814
Revises: e8101fbc5d12
Create Date: 2025-05-03 20:36:24.594313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0ceda47814'
down_revision: Union[str, None] = 'e8101fbc5d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('custom_message', sa.String(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('last_video_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_channel_id', 'youtube_channel_id', name='uix_discord_channel_youtube_channel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_notifications')
    # ### end Alembic commands ###
