"""add_welcome_message_table

Revision ID: 53e8778c2f7a
Revises: 1a0ceda47814
Create Date: 2025-11-21 16:42:18.210874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e8778c2f7a'
down_revision: Union[str, None] = '1a0ceda47814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('welcome_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id'),
    sa.UniqueConstraint('guild_id', name='uix_guild_welcome_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('welcome_messages')
    # ### end Alembic commands ###
