"""add unique constraint to member table

Revision ID: e8101fbc5d12
Revises: 4c3a345681f5
Create Date: 2024-11-30 16:02:34.782831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8101fbc5d12'
down_revision: Union[str, None] = '4c3a345681f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'activities', 'members', ['member_id'], ['id'])
    op.create_unique_constraint('uix_userid_guild_id', 'members', ['user_id', 'guild_id'])
    op.create_foreign_key(None, 'modwarnings', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modwarnings', type_='foreignkey')
    op.drop_constraint('uix_userid_guild_id', 'members', type_='unique')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    # ### end Alembic commands ###
